/**
 * Catálogo controlado de tipos de arte/manifestações artísticas.
 *
 * Lista abrangente que inclui:
 * - Belas artes consagradas (pintura, escultura, música)
 * - Artes performáticas (teatro, dança, circo)
 * - Artesanato manual (bordado, crochê, cerâmica, pipas)
 * - Cultura popular brasileira (frevo, maracatu, capoeira)
 * - Artes digitais e tecnologias criativas (animação 3D, game art)
 * - Trabalhos manuais menos óbvios mas com valor artístico (velas,
 *   sabonetes, decoração de eventos, jardinagem ornamental)
 *
 * Atualizações futuras: adicionar/remover items aqui que o seletor
 * pega automaticamente. Backend não tem enum — aceita qualquer string.
 */

export interface CategoriaArte {
  id: string;
  label: string;
  items: string[];
}

export const TIPOS_ARTE: CategoriaArte[] = [
  {
    id: "visuais",
    label: "Artes Visuais",
    items: [
      "Pintura",
      "Pintura a óleo",
      "Pintura acrílica",
      "Aquarela",
      "Pintura mural",
      "Grafite / Street art",
      "Desenho",
      "Ilustração",
      "Quadrinhos / HQ",
      "Mangá",
      "Caricatura",
      "Gravura",
      "Xilogravura",
      "Serigrafia",
      "Linogravura",
      "Litografia",
      "Colagem",
      "Arte abstrata",
      "Arte conceitual",
      "Arte digital",
      "Pixel art",
      "Tatuagem",
      "Maquiagem artística",
      "Body painting",
    ],
  },
  {
    id: "escultura",
    label: "Escultura e Modelagem",
    items: [
      "Escultura em madeira",
      "Escultura em pedra",
      "Escultura em metal",
      "Esculturas em areia",
      "Esculturas em gelo",
      "Cerâmica",
      "Modelagem em argila",
      "Biscuit",
      "Origami",
      "Papel machê",
      "Esculturas em balão",
      "Esculturas em frutas e vegetais",
      "Bonsai",
    ],
  },
  {
    id: "fotografia",
    label: "Fotografia e Audiovisual",
    items: [
      "Fotografia de eventos",
      "Fotografia de casamento",
      "Fotografia de retrato",
      "Fotografia de moda",
      "Fotografia gastronômica",
      "Fotografia de produto",
      "Fotojornalismo",
      "Fotografia de natureza",
      "Fotografia de rua",
      "Videomaking",
      "Edição de vídeo",
      "Animação",
      "Motion design",
      "Direção de cinema",
      "Roteiro",
      "Sound design",
    ],
  },
  {
    id: "musica",
    label: "Música",
    items: [
      "Canto / Vocal",
      "Violão",
      "Guitarra",
      "Baixo",
      "Bateria",
      "Piano",
      "Teclado",
      "Saxofone",
      "Trompete",
      "Trombone",
      "Flauta",
      "Clarinete",
      "Violino",
      "Violoncelo",
      "Harpa",
      "Acordeon",
      "Cavaquinho",
      "Bandolim",
      "Ukulele",
      "Berimbau",
      "Percussão",
      "DJ",
      "Beatbox",
      "Composição",
      "Arranjo musical",
      "Regência / Maestro",
      "Coral",
      "Produção musical",
      "Aulas de música",
    ],
  },
  {
    id: "cenicas",
    label: "Artes Cênicas e Performance",
    items: [
      "Teatro",
      "Teatro infantil",
      "Teatro de bonecos / Marionetes",
      "Stand-up comedy",
      "Improviso",
      "Mímica",
      "Palhaço",
      "Performance art",
      "Dramaturgia",
      "Direção teatral",
      "Ópera",
    ],
  },
  {
    id: "danca",
    label: "Dança",
    items: [
      "Ballet clássico",
      "Dança contemporânea",
      "Jazz",
      "Sapateado",
      "Hip-hop",
      "Break / Breakdance",
      "Forró",
      "Samba",
      "Salsa",
      "Bachata",
      "Tango",
      "Zumba",
      "Dança do ventre",
      "Dança de salão",
      "Dança afro",
      "K-pop",
      "Dança aérea (tecidos / lira)",
    ],
  },
  {
    id: "circo",
    label: "Circo",
    items: [
      "Acrobacia",
      "Malabares",
      "Equilibrismo",
      "Trapézio",
      "Tecido acrobático",
      "Lira / Aro aéreo",
      "Roda Cyr",
      "Monociclo",
      "Cuspidor de fogo",
      "Faquir",
    ],
  },
  {
    id: "literatura",
    label: "Literatura e Palavra",
    items: [
      "Poesia",
      "Slam / Spoken word",
      "Cordel",
      "Contação de histórias",
      "Crônica",
      "Romance",
      "Roteiro de quadrinhos",
      "Escrita criativa",
      "Revisão / Edição literária",
      "Tradução literária",
    ],
  },
  {
    id: "texteis",
    label: "Artesanato Têxtil e Moda",
    items: [
      "Bordado",
      "Bordado livre",
      "Ponto cruz",
      "Crochê",
      "Tricô",
      "Amigurumi",
      "Macramê",
      "Tear",
      "Tapeçaria / Tapetes",
      "Patchwork",
      "Costura criativa",
      "Renda / Renda de bilro",
      "Filé",
      "Estilismo",
      "Modelagem de roupas",
      "Customização de roupas",
      "Tingimento natural / Tie-dye",
      "Estamparia",
      "Confecção de figurinos",
    ],
  },
  {
    id: "artesanato",
    label: "Artesanato Tradicional",
    items: [
      "Cerâmica artística",
      "Cerâmica utilitária",
      "Olaria",
      "Porcelana pintada",
      "Vitrais",
      "Mosaico",
      "Marchetaria",
      "Encadernação artesanal",
      "Cartonagem",
      "Couraria",
      "Sapataria artesanal",
      "Acessórios em couro",
      "Cestaria",
      "Vime e junco",
      "Trançados naturais",
      "Joalheria",
      "Bijuteria artesanal",
      "Ourivesaria",
      "Lapidação",
      "Soutache",
      "Velas artesanais",
      "Sabonetes artesanais",
      "Cosméticos naturais artesanais",
      "Brinquedos artesanais em madeira",
      "Bonecas artesanais",
      "Brinquedos em tecido",
      "Pipas",
    ],
  },
  {
    id: "gastronomia",
    label: "Gastronomia Artística",
    items: [
      "Confeitaria artística",
      "Cake design / Bolos decorados",
      "Cupcakes decorados",
      "Chocolataria artística",
      "Latte art",
      "Esculturas em frutas (Mukimono)",
      "Decoração de mesa / Buffet",
      "Doces finos",
      "Pão artístico",
    ],
  },
  {
    id: "design",
    label: "Design, Decoração e Caligrafia",
    items: [
      "Design gráfico",
      "Design de interiores",
      "Design de produto",
      "Web design",
      "UX/UI design",
      "Decoração de eventos",
      "Decoração de festas infantis",
      "Cenografia",
      "Arranjos florais",
      "Floricultura artística",
      "Buquês",
      "Jardinagem ornamental",
      "Paisagismo",
      "Caligrafia",
      "Caligrafia chinesa / japonesa",
      "Hand lettering",
      "Brush lettering",
      "Tipografia",
    ],
  },
  {
    id: "popular",
    label: "Cultura Popular Brasileira",
    items: [
      "Maracatu",
      "Boi-bumbá / Bumba meu boi",
      "Quadrilha junina",
      "Frevo",
      "Carimbó",
      "Coco",
      "Reisado",
      "Capoeira (performance)",
      "Cordel",
      "Repente / Embolada",
    ],
  },
  {
    id: "tecnologia",
    label: "Tecnologias Criativas e Arte Digital",
    items: [
      "Modelagem 3D",
      "Impressão 3D artística",
      "Animação digital",
      "Vídeo mapping",
      "Realidade aumentada artística",
      "Concept art",
      "Game art",
      "NFT / Crypto art",
      "Arte generativa",
    ],
  },
  {
    id: "sustentavel",
    label: "Arte Ambiental e Sustentável",
    items: [
      "Arte com materiais reciclados",
      "Land art",
      "Arte ambiental",
      "Upcycling",
      "Mosaico com cerâmica reaproveitada",
    ],
  },
  {
    id: "outros",
    label: "Outros",
    items: [
      "Outras artes visuais",
      "Outro instrumento musical",
      "Outro estilo de dança",
      "Outras artes performáticas / Circo",
      "Outro artesanato manual",
      "Outras artes audiovisuais",
      "Outras artes literárias",
      "Outra modalidade gastronômica",
      "Outro design ou decoração",
      "Outra manifestação cultural",
      "Outras (especifique na sua bio)",
    ],
  },
];

/** Lista plana de todos os tipos — útil pra validação ou lookup rápido. */
export const TODOS_TIPOS_ARTE: string[] = TIPOS_ARTE.flatMap((c) => c.items);

/** Set pra checar em O(1) se um tipo é canônico (vem da lista oficial). */
export const TIPOS_ARTE_SET = new Set(TODOS_TIPOS_ARTE);
